[package]
name = "cryptoy"
version = "0.1.0"
authors = ["Jesper Foldager <jifoldager@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
aes-gcm-siv = "0.9.0"
rand = "0.7.3"
